version: '3.8'

services:

  postgres:

    image: postgres:latest

    container_name: archlab6

    environment:
      POSTGRES_PASSWORD: "password"
      
    ports:
      - "5432:5432"

    volumes:
     - lab6pgdata:/var/lib/postgresql/data
volumes:
  lab6pgdata: